Blackfin: add elf_machine_load_address() stub
The Blackfin port never defined elf_machine_load_address() because the one
place this code is called never matters to us.  But without it, common code
likes to hit a build failure, so stub it out.

ldso/ldso/dl-startup.c: In function '_dl_start':
ldso/ldso/dl-startup.c:170: warning: implicit declaration of function 'elf_machine_load_address'

Signed-off-by: Mike Frysinger <vapier@gentoo.org>