ldso_tls: fix compiler warning due to missing cast
Fix compiler warning (as below) due to missign cast

In file included from ldso/ldso/ldso.c:42:0:
ldso/ldso/dl-tls.c: In function 'init_tls':
ldso/ldso/dl-tls.c:1028:24: error: initialization makes pointer from integer without a cast

Signed-off-by: Carmelo Amoroso <carmelo.amoroso@st.com>